AWSTemplateFormatVersion: 2010-09-09

Transform:
  Name: AWS::Include
  Parameters:
    Location: s3://puttest/binary.yaml

Parameters:
  EmailAddress:
    Type: String
    Description: SNS nortification will be send to email address
  AllowedIpAddress:
    Type: String
    AllowedPattern: \d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}/\d{1,2}
    Description: Ip address that is allowed to connect S3 bucket
    
Resources:
  TestPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
     ArtifactStore:
       Location: !Ref ArtifactStoreBucket
       Type: S3
     RoleArn: !GetAtt TestRole.Arn
     Stages:
       - Name: Source
         Actions:
           - Name: SourceAction
             ActionTypeId:
               Category: Source
               Owner: AWS
               Provider: CodeCommit
               Version: 1
             Configuration:
               RepositoryName: bin-test
               BranchName: master
               PollForSourceChanges: True
             OutputArtifacts:
               - Name: SourceOutput
             RunOrder: 1
       - Name: Build
         Actions:
           - Name: BuildAction
             ActionTypeId:
               Category: Build
               Owner: AWS
               Provider: CodeBuild
               Version: 1
             Configuration:
               ProjectName: !Ref BinBuild
             InputArtifacts:
               - Name: SourceOutput
             OutputArtifacts:
               - Name: artifact1
               - Name: artifact2
             RunOrder: 1
       - Name: InfraDeploy
         Actions:
           - Name: CreateChangeSet
             ActionTypeId:
               Category: Deploy
               Owner: AWS
               Provider: CloudFormation
               Version: 1
             Configuration:
               ActionMode: CHANGE_SET_REPLACE
               Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
               ChangeSetName: bin-test-changeset
               ParameterOverrides: !Sub '{"EmailAddress": "${EmailAddress}","AllowedIpAddress": "${AllowedIpAddress}"}'
               RoleArn: !GetAtt BinCloudformationServiceRole.Arn
               StackName: bin-test
               TemplatePath: 'artifact2::template/binary.yaml'
             InputArtifacts:
               - Name: artifact2
             RunOrder: 1
           - Name: ExecuteChangeSet
             ActionTypeId:
               Category: Deploy
               Owner: AWS
               Provider: CloudFormation
               Version: 1
             Configuration:
               ActionMode: CHANGE_SET_EXECUTE
               Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
               ChangeSetName: bin-test-changeset
               StackName: bin-test
             InputArtifacts:
               - Name: artifact2
             RunOrder: 2
       - Name: AppDeploy
         Actions:
           - Name: DeployAction
             ActionTypeId:
               Category: Deploy
               Owner: AWS
               Provider: S3
               Version: 1
             Configuration:
               BucketName:
                 Fn::ImportValue:  bin-test-BinBucketName
               Extract: true
             InputArtifacts:
               - Name: artifact1
             RunOrder: 1
     Tags:
       - Key: pjt
         Value: test
         
  BinBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: build project for bin test
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: REGION
            Type: PLAINTEXT
            Value: !Ref AWS::Region
        Image: aws/codebuild/amazonlinux2-x86_64-standard:2.0
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt BinBuildServiceRole.Arn
      Source:
        BuildSpec: config/buildspec_cicd.yaml
        Type: CODEPIPELINE
      Tags:
        - Key: pjt
          Value: test
        
  BinBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: my-test-bin
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
        
  BinCloudformationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: my-test-bin
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
                
  TestRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: my-test-bin
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
     
  ArtifactStoreBucket:
    Type: AWS::S3::Bucket