AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  TargetDB:
    Type: String
    Default: stream-test
  TargetRegion:
    Type: String
    Default: us-west-2
    AllowedValues:
      - eu-north-1
      - ap-south-1
      - eu-west-3
      - eu-west-2
      - eu-west-1
      - ap-northeast-2
      - ap-northeast-1
      - sa-east-1
      - ca-central-1
      - ap-southeast-1
      - ap-southeast-2
      - eu-central-1
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./app
      Description: keep 2 DynamoDB tables in sync via DynamoDB Stream
      Environment:
        Variables: 
          TargetDB:
            Ref: TargetDB
          TargetRegion:
            Ref: TargetRegion
      Events:
        DDBEvent:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::Sub: ${DDB.StreamArn}
            StartingPosition: TRIM_HORIZON
            BatchSize: 10
            Enabled: true
      Handler: index.handler
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:DeleteItem
                - dynamodb:UpdateItem
              Resource:
                - Fn::Sub: arn:aws:dynamodb:${TargetRegion}:${AWS::AccountId}:table/${TargetDB}
      Runtime: python3.8
      Tags:
        pjt: lambda-ddb-stream
      Timeout: 5
  
  DDB:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      BillingMode: PROVISIONED
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags: 
        - Key: pjt
          Value: lambda-ddb-stream