AWSTemplateFormatVersion: 2010-09-09
Parameters:
  NetworkAcl:
    Type: String
  SSHPort:
    Type: String
    
Resources:
  InboundRule01:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId:
        Ref: NetworkAcl
      PortRange: 
        From:
          Ref: SSHPort
        To:
          Ref: SSHPort
      Protocol: 6
      RuleAction: allow
      RuleNumber: 100
        
  InboundRule02:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId:
        Ref: NetworkAcl
      PortRange: 
        From: 32768
        To: 65535
      Protocol: 6
      RuleAction: allow
      RuleNumber: 110
        
  InboundRule03:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 180.233.109.229/32
      Egress: false
      NetworkAclId:
        Ref: NetworkAcl
      PortRange: 
        From: 50000
        To: 50100
      Protocol: 17
      RuleAction: allow
      RuleNumber: 120
        
  OutboundRule01:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId:
        Ref: NetworkAcl
      PortRange: 
        From: 80
        To: 80
      Protocol: 6
      RuleAction: allow
      RuleNumber: 100
        
  OutboundRule02:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId:
        Ref: NetworkAcl
      PortRange: 
        From: 443
        To: 443
      Protocol: 6
      RuleAction: allow
      RuleNumber: 110
        
  OutboundRule03:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId:
        Ref: NetworkAcl
      PortRange: 
        From: 32768
        To: 65535
      Protocol: 6
      RuleAction: allow
      RuleNumber: 120
        
  OutboundRule04:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 180.233.109.229/32
      Egress: true
      NetworkAclId:
        Ref: NetworkAcl
      PortRange: 
        From: 4172
        To: 4172
      Protocol: 6
      RuleAction: allow
      RuleNumber: 130
        
  OutboundRule05:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 180.233.109.229/32
      Egress: true
      NetworkAclId:
        Ref: NetworkAcl
      PortRange: 
        From: 4172
        To: 4172
      Protocol: 17
      RuleAction: allow
      RuleNumber: 140