AWSTemplateFormatVersion: 2010-09-09
Parameters:
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
  PubKey:
    Type: String
    Description: Public key to be added as authorized key
  SSHLocation:
    Type: String
    Description: IP address to allow ssh
  SSHPort:
    Type: String
    Description: TCP port for sshd
  NaclRulesTemplateUrl:
    Type: String
  InstanceTemplateUrl:
    Type: String

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 192.168.0.0/24
      Tags: 
        - Key: Name
          Value: win-vpc
          
  Subnet:
    Type: AWS::EC2::Subnet
    Properties: 
      CidrBlock: 192.168.0.0/28
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: win-subnet
      VpcId:
        Ref: Vpc
        
  Igw:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key: Name
          Value: win-igw
          
  VpcAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId:
        Ref: Igw
      VpcId:
        Ref: Vpc
  
  RoutingTable:
    Type: AWS::EC2::RouteTable
    Properties: 
      Tags: 
        - Key: Name
          Value: win-rt
      VpcId:
        Ref: Vpc
        
  Route:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: Igw
      RouteTableId:
        Ref: RoutingTable
        
  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId:
        Ref: RoutingTable
      SubnetId:
        Ref: Subnet
  
  NetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties: 
      Tags: 
        - Key: Name
          Value: win-nacl
      VpcId:
        Ref: Vpc
      
  NaclRules:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        NetworkAcl:
          Ref: NetworkAcl
        SSHPort:
          Ref: SSHPort
      TemplateURL:
        Ref: NaclRulesTemplateUrl
      
  SubnetNetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties: 
      NetworkAclId:
        Ref: NetworkAcl
      SubnetId:
        Ref: Subnet
            
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: win-sg
      GroupName: win-sg
      SecurityGroupIngress:
        - CidrIp:
            Ref: SSHLocation
          FromPort:
            Ref: SSHPort
          IpProtocol: tcp
          ToPort:
            Ref: SSHPort
      VpcId:
        Ref: Vpc

  InstanceWithProfile:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        KeyPair:
          Ref: KeyPair
        PubKey:
          Ref: PubKey
        SSHPort:
          Ref: SSHPort
        Subnet:
          Ref: Subnet
        SecurityGroup:
          Ref: SecurityGroup
      TemplateURL:
        Ref: InstanceTemplateUrl